export GOOS=windows
export GOARCH=amd64
export CGO_ENABLED=1
export CC=x86_64-w64-mingw32-gcc

AR=x86_64-w64-mingw32-ar
CFLAGS=-I../hidapi/hidapi -g -c

OBJS=../hidapi/windows/hid.o

BUILD=./build/windows/

all: hidtest

hidtest: libhidapi.a
	go build -o $(BUILD) cmd/hidtest/hidtest.go

libhidapi.a: $(OBJS)
	@mkdir -p $(BUILD)
	$(AR) rcs $(BUILD)$@ $<

$(OBJS): %.o: %.c
	$(CC) $(CFLAGS) $< -o $@

clean:
	@rm -rf $(BUILD)
	@rm -f $(OBJS) 

.PHONY: all clean
